Repository intlify/vue-i18n-extensions, pull requests merged in 2022-12, with the labels that each got.

#168 drop node v12
  .github/workflows/test.yml
  package.json
  yarn.lock
Labels: Type: Breaking

#173 feat: support Vue 3.2
  package.json
  test/__snapshots__/pre-translation.test.ts.snap
  test/__snapshots__/transform.test.ts.snap
  yarn.lock
Labels: Type: Feature

#175 chore: add lint cache
  .gitignore
  package.json
Labels: Type: Maintenance

#176 fix: typo
  src/report.ts
  src/transform.ts
  src/transpiler.ts
  test/transform.test.ts
Labels: Type: Improvement
